<?php

/**
 * @file
 * Primary module hooks for 01 Hello World! module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_help().
 */
function hello_world_help(
  $route_name,
  \Drupal\Core\Routing\RouteMatchInterface $route_match
) {
  switch ($route_name) {
    case 'help.page.hello_world':
      return '<p>'.t('Notre premier module Drupal ne possède pas grand chose').'</p>';
  }
  return null;
}

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path) {
  return [
    'example' => [ // le nom du template est par défaut la clé du type de rendu
      'variables' => [ //les variables mises à disposition du template doivent être déclarées ici
        'my_var1' => '',
      ]
    ],
  ];
}
