<?php

/**
 * @file
 * Primary module hooks for 01 Hello World! module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_help().
 */
function hello_world_help(
  $route_name,
  \Drupal\Core\Routing\RouteMatchInterface $route_match
) {
  switch ($route_name) {
    case 'help.page.hello_world':
      return '<p>'.t('Notre premier module Drupal ne possède pas grand chose').'</p>';
  }
  return null;
}
